spring:
  application:
    name: integraservicios

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        proc.param_null_passing: true
        temp.use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://${db_host}:${db_port}/${db_name}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: ${api_context_path}

logging:
  file:
    name: ${api_file_logs}
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"

  level:
    org.springframework.web: ERROR
    com.howtodoinjava: INFO
    org.hibernate: ERROR
